# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'my_covid19_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for my_covid19_app

  pod 'Alamofire', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'

end
